### PR TITLE
Remove dependency on $.browser

### PR DESCRIPTION
**Pull request by fofr**
Extract the `$.browser` logic and tests into a shim and replace `$.browser` calls with `window.NOMENSA.browser` ones.

The browser based tests are still needed to identify [Firefox versions with a known flash bug](https://bugzilla.mozilla.org/show_bug.cgi?id=78414) that interferes with SWFObject. This can't easily be handled using feature detection.

There are also MSIE tests which add classes for styling, the default styles use these to trigger `hasLayout`.

Includes whitespace changes, recommend reviewing using `?w=1`

EDIT: Tested on Static and https://wwww.gov.uk/government/news/ramadan-2015-david-camerons-message

### CODE REVIEW

**Comment by tombye** [comment]
This is really nice reading - very clear what the changes are.

Apart from my one question (as a comment) LGMT :+1:

**Comment by dsingleton** [comment]
The changes look good to me, especially the testing :+1: 

I checked this out locally to run the tests (with `./run_tests.sh` and i'm seeing (unrelated) failures on this branch and master. 

```jquery.player tests (integration) : should not call the YoutubePlayer constructor when using Vimeo
TypeError: 'null' is not an object (evaluating 'media.container')```

I think I may be missing a setup step, but i'm assuming they pass locally for you?

It would be good to have CI for this repo, not a blocker for this PR if the tests do pass, but worth adding for general confidence, given this a repo we touch irregularly. 

(Top commits btw, this was a pleasure to review)

**Comment by fofr** [comment]
@dsingleton The unrelated test failure is also failing on master, and is probably related to a change in an external Vimeo API since the tests were written – which I discussed with @tombye. I've left out fixing that test from this PR because it's unrelated, but it should be put right.

This is a repo we've previously pushed upstream (and I'd like to push these changes too), which is something to consider when setting up CI.

**Comment by dsingleton** [comment]
In which case i'm happy to merge this, and if we can add CI, fix the test and push upstream, then those are all bonuses.

**Pull request merged**
